### ISSUE TITLE
Club Funding ne fonctionne plus

### ISSUE THREAD

**Issue by mickaelv** [abrisse/finary#2]
Bonjour,

il semblerai que l'import de Club Funding ne fonctionne plus.

L'API semble avoir changé d'URL : https://api.clubfunding.fr/v2 et non plus https://api.clubfunding.fr/api/

Je n'ai pas pu tester le fix.

**Comment by abrisse** [comment]
Bonjour @mickaelv.

En effet l'API a complètement changé. C'est corrigé avec le commit 57927543ed16bc6f3237d67e89e99b2efee4eb20.
